### ISSUE TITLE
Error in Status Line

### ISSUE THREAD

**Issue by JustAnother1** [chickenchuck040/octoscreen#2]
At that time Octoprint had a communication error. Question is is displaying the error in this form intentional?
![20170112_002001](https://cloud.githubusercontent.com/assets/695780/21870663/d2104870-d85d-11e6-908e-6cddc5fa313b.jpg)

**Comment by timothyhollabaugh** [comment]
Yes, it does that. This happens when Octoprint puts an error into the human readable status of the printer (such as a printer unexpectedly disconnecting), but Octoscreen is not expecting a status to be that long. I believe there is another instance of this bug where the display will say `alive?` if the printer has not responded in a while.

**Comment by timothyhollabaugh** [comment]
This should be fixed in the latest commit
